### ISSUE TITLE
setsocketopt

### ISSUE THREAD

**Issue by FRNCSCM** [eiunkar/pyNakadi#9] opened 2019-03-02 11:35 UTC
Hi,
 
I'm trying to read a Nakadi event, but the client just yields the following error messages:

`Exception has occurred: UnboundLocalError
local variable 'subscription' referenced before assignment
  File "/Users/.git/folder/old /read_nakadi.py", line 38, in get_batch
    subscription.close()
  File "/Users/.git/folder/old /read_nakadi.py", line 51, in <module>
    batch, stream_id = get_batch(token, host, subscription_id, 10)
  File "/Users/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/anaconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/anaconda3/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)`

and

`Exception while fetching events from Nakadi
Traceback (most recent call last):
  File "/Users/.git/folder/old /read_nakadi.py", line 31, in get_batch
    subscription = get_subscription(token, host, subscription_id, limit)
  File "/Users/.git/folder/old /read_nakadi.py", line 20, in get_subscription
    sub = client.get_subscription_events_stream(subscription_id, batch_limit=limit, stream_limit=limit)
  File "/Users/anaconda3/lib/python3.7/site-packages/pyNakadi/client.py", line 634, in get_subscription_events_stream
    return NakadiStream(response)
  File "/Users/anaconda3/lib/python3.7/site-packages/pyNakadi/client.py", line 40, in __init__
    self.sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
AttributeError: 'WrappedSocket' object has no attribute 'setsockopt'`

Can anyone help me with this issue?

**Comment by eiunkar** [comment] 2019-03-17 09:51
Hello,
As far as I remember @dmigo solved this issue. Since package is not published for a long time, if you use version 0.2.12 from pypi repo (it seems so because error number lines are not in sync with latest commits), you may hit this issue. Today I published version 0.2.13 where @dmigo 's fixing change is included. I am closing this issue, if you see this error with with version 0.2.13, please reopen.

**Comment by FRNCSCM** [comment] 2019-03-18 15:18
Hi Ersin,

thanks for the reply.

Unfortunately, it doesn't work.

I did install pyNakadi==0.2.13, but it just gives back the same error.
The buffer of the NakadiStream class is still empty - and I made sure that there are events under my subscription.

**Comment by eiunkar** [comment] 2019-03-19 08:25
Hello,
Could you post me your python environment? Which python version? If it is conda, please send me the command for creating your env. And additionally your requirements.txt file.
It may take some time to reproduce your issue.
@dmigo is the most experienced/active user and developer in pyNakadi community currently. We may also consult him if he verifies this issue. He may recommend you a python environment that he sees working properly.
I hope he answers :), he may be busy.

**Comment by eiunkar** [comment] 2019-04-02 07:47
No env response from reporter. Closing this until response reaches.

**Closed by eiunkar** 2019-04-02 07:47 UTC
